/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  RewardsToken,
  RewardsTokenInterface,
} from "../../../contracts/Staking_Pool.sol/RewardsToken";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class RewardsToken__factory {
  static readonly abi = _abi;
  static createInterface(): RewardsTokenInterface {
    return new utils.Interface(_abi) as RewardsTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RewardsToken {
    return new Contract(address, _abi, signerOrProvider) as RewardsToken;
  }
}
