/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as stakingPoolSol from "./Staking_Pool.sol";

export type { stakingPoolSol };
export type { ERC20_Token } from "./ERC20_Token";
export type { ERC721_NFT } from "./ERC721_NFT";
